name: copy to github pages
on:
  push:
    branches:
    - 'main'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout main branch
        with:
          ref: main
      - name: push to gh-pages
        run: |
          git config --global user.email "3002590@school.ecsd.net"
          git config --global user.name "Github Actions autodeploy"
          git add dist
          git commit -m "autodeploy project to GitHub Pages"
          git subtree push --prefix dist origin gh-pages
